services:
  db:
    image: postgres:18-alpine
    restart: always
    container_name: blog-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


